nama=input("nama kamu siapa:")
sekolah=input("kamu sekolah dimana:")
kelas=input("kamu kelas berapa:")
jurusan=input("kamu jurusan apa:")
umur=input("umur kamu berapa:")
hobi=input("hobi kamu apa:")
tontonan_fav=input("apa tontonan fav kamu:")
jenis_musik_fav=input("apa jenis musik fav kamu:")
makanan_fav=input("apa makanan fav kamu:")
alamat=input("dimana alamat rumah kamu:")
print("nama saya adalah",nama,"sekolah saya adalah",sekolah,"saya kelas",kelas,"saya jurusan",jurusan,"umur saya",umur,"hobi saya",hobi,"tontonan_fav_saya",tontonan_fav,"jenis_musik_fav_saya",jenis_musik_fav,"makanan_fav_saya",makanan_fav,"alamat saya",alamat,)